<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <VersionPrefix>0.7.0</VersionPrefix>
    <VersionSuffix>prototipo</VersionSuffix>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ProductReleaseDate>2026-09-26</ProductReleaseDate>
    <UpdateChannel>Prototype</UpdateChannel>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="ReleaseDate" Value="$(ProductReleaseDate)" />
    <AssemblyMetadata Include="UpdateChannel" Value="$(UpdateChannel)" />
    <AssemblyMetadata Include="RepositoryOwner" Value="guiasysstudio" />
    <AssemblyMetadata Include="RepositoryName" Value="GuiaPlay" />
  </ItemGroup>
</Project>
